// Code generated by status-rules-codegen from spec/rules.yaml v1.0.0. DO NOT EDIT.
//
// Source: github.com/logistics-oss/status-rules/spec/rules.yaml
// Generator: logistics-oss/status-rules-codegen
//
// To regenerate: update spec/rules.yaml and run `go generate` in the module root.

package status

// Status represents a canonical shipment status code.
// The zero value (0) is intentionally uninitialized — no valid status has ID 0.
// All valid status IDs are in the range [1, 55].
type Status uint8

// String returns the canonical string code for a status.
// Returns "<unknown>" for unrecognized values.
func (s Status) String() string {
	if int(s) < len(statusNames) {
		return statusNames[s]
	}
	return "<unknown>"
}

// statusNames maps Status → canonical string code. Index 0 is the zero sentinel.
var statusNames = [56]string{
	0:  "",                   // zero value — uninitialized
	1:  "DRAFT",
	2:  "BOOKED",
	3:  "PART_PAYMENT_PENDING",
	4:  "UPDATED_BOOKING",
	5:  "MANIFESTED",
	6:  "READY_FOR_PICKUP",
	7:  "INSCANNED",
	8:  "HUB-IN-SCANNED",
	9:  "BAGGED",
	10: "BAG_CREATED",
	11: "BAG_FINALISED",
	12: "BAG_DELETED",
	13: "INSCANNED_AT_TRANSIT",
	14: "HUB-OUTSCAN",
	15: "REMOVED_FROM_BAG",
	16: "REMOVED_FROM_LCR",
	17: "IN-BAG-INSCAN",
	18: "IN-BAG-OUTSCAN",
	19: "IN_BAG_OUTSCAN_TO_CP",
	20: "OUT_SCAN_TO_CP",
	21: "OUT_SCAN_TO_3PL",
	22: "INSCANNED_AT_CP",
	23: "SCHEDULED_FOR_TRIP",
	24: "OUT_FOR_DELIVERY",
	25: "ATTEMPTED",
	26: "UNDELIVERED",
	27: "RETURN_INITIATED",
	28: "RETURN_REVOKED",
	29: "DELIVERED",
	30: "RTO_DELIVERED",
	31: "CANCELLED",
	32: "REJECTED",
	33: "REJECTED_BY_HO",
	34: "RTO",
	35: "RTO_OUT_FOR_DELIVERY",
	36: "RTO_UNDELIVERED",
	37: "DAMAGED",
	38: "MIS_ROUTED",
	39: "REROUTED",
	40: "EXCESS_INSCAN",
	41: "PINCODE_AUDITED",
	42: "WEIGHT_AUDITED",
	43: "MODE_AUDITED",
	44: "FORCE_HUB_OUTSCAN",
	45: "FORCE_BAG",
	46: "FORCE_BAG_ATTEMPTED",
	47: "FORCE_OUTSCAN_TO_CP",
	48: "3PL_ITEM_BOOK",
	49: "3PL_ITEM_DELIVERY",
	50: "3PL_ITEM_ONHOLD",
	51: "3PL_ITEM_REDIRECT",
	52: "3PL_ITEM_RETURN",
	53: "3PL_BAG_CLOSE",
	54: "3PL_BAG_DISPATCH",
	55: "3PL_BAG_OPEN",
}

// Status constants. Values are spec YAML id + 1.
// The +1 offset reserves Status(0) as the Go zero-value sentinel.
// These values are stable — never renumber them.
const (
	// ORDER_BOOKING / PRE_MILE
	Draft              Status = 1  // YAML id: 0
	Booked             Status = 2  // YAML id: 1
	PartPaymentPending Status = 3  // YAML id: 2
	UpdatedBooking     Status = 4  // YAML id: 3
	Manifested         Status = 5  // YAML id: 4

	// FIRST_MILE
	ReadyForPickup Status = 6  // YAML id: 5
	Inscanned      Status = 7  // YAML id: 6

	// MIDDLE_MILE
	HubInScanned       Status = 8  // YAML id: 7  — "HUB-IN-SCANNED"
	Bagged             Status = 9  // YAML id: 8
	BagCreated         Status = 10 // YAML id: 9
	BagFinalised       Status = 11 // YAML id: 10
	BagDeleted         Status = 12 // YAML id: 11
	InscannedAtTransit Status = 13 // YAML id: 12
	HubOutscan         Status = 14 // YAML id: 13 — "HUB-OUTSCAN"
	RemovedFromBag     Status = 15 // YAML id: 14
	RemovedFromLCR     Status = 16 // YAML id: 15
	InBagInscan        Status = 17 // YAML id: 16 — "IN-BAG-INSCAN"
	InBagOutscan       Status = 18 // YAML id: 17 — "IN-BAG-OUTSCAN"
	InBagOutscanToCP   Status = 19 // YAML id: 18
	OutScanToCP        Status = 20 // YAML id: 19
	OutScanTo3PL       Status = 21 // YAML id: 20

	// LAST_MILE
	InscannedAtCP    Status = 22 // YAML id: 21
	ScheduledForTrip Status = 23 // YAML id: 22
	OutForDelivery   Status = 24 // YAML id: 23
	Attempted        Status = 25 // YAML id: 24
	Undelivered      Status = 26 // YAML id: 25
	ReturnInitiated  Status = 27 // YAML id: 26
	ReturnRevoked    Status = 28 // YAML id: 27

	// TERMINAL
	Delivered    Status = 29 // YAML id: 28 — terminal
	RTODelivered Status = 30 // YAML id: 29 — terminal
	Cancelled    Status = 31 // YAML id: 30 — terminal
	Rejected     Status = 32 // YAML id: 31 — terminal
	RejectedByHO Status = 33 // YAML id: 32 — terminal

	// RTO / REVERSE
	RTO               Status = 34 // YAML id: 33
	RTOOutForDelivery Status = 35 // YAML id: 34
	RTOUndelivered    Status = 36 // YAML id: 35

	// EXCEPTION WILDCARDS — valid destination from any non-terminal status
	Damaged       Status = 37 // YAML id: 36
	MisRouted     Status = 38 // YAML id: 37
	Rerouted      Status = 39 // YAML id: 38
	ExcessInscan  Status = 40 // YAML id: 39
	PincodeAudit  Status = 41 // YAML id: 40
	WeightAudit   Status = 42 // YAML id: 41
	ModeAudit     Status = 43 // YAML id: 42

	// FORCE_* OVERRIDES — first-class edges requiring operator_id
	ForceHubOutscan   Status = 44 // YAML id: 43
	ForceBag          Status = 45 // YAML id: 44
	ForceBagAttempted Status = 46 // YAML id: 45
	ForceOutscanToCP  Status = 47 // YAML id: 46

	// 3PL
	ThreePLItemBook     Status = 48 // YAML id: 47
	ThreePLItemDelivery Status = 49 // YAML id: 48 — terminal
	ThreePLItemOnhold   Status = 50 // YAML id: 49
	ThreePLItemRedirect Status = 51 // YAML id: 50
	ThreePLItemReturn   Status = 52 // YAML id: 51
	ThreePLBagClose     Status = 53 // YAML id: 52
	ThreePLBagDispatch  Status = 54 // YAML id: 53
	ThreePLBagOpen      Status = 55 // YAML id: 54
)

// MaxID is the highest valid Status value. Used for bounds checks.
const MaxID Status = 55
